name: YAML Validation

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run YAML linter
        run: |
          yamllint --list-files .
          yamllint -d "{
            extends: default,
            rules: {
              line-length: disable,
              document-start: {present: false},
              truthy: {check-keys: false}
            }
          }" .
